### ISSUE TITLE
Create JavaScript Program 

### ISSUE THREAD

**Issue by JohnnieEmmanuel** [Yashkapure06/GDSC-ProCode#167]
To compliment the availability to c, CPP and java codes, I will love to add JavaScript codes solving the problem for the day

**Comment by JohnnieEmmanuel** [comment]
Please assign this task to me. Thank you

**Comment by Yashkapure06** [comment]
OKay You can go ahead! Just Fork this repo. See the Problem statement in Readme.md of respective folder of respective date and just add your files and after making changes raise A PR(Pull Request) If found your code to be correct we will merge your solution
